spring:
  application:
    name: board-game-buddy

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:placeholder-key}
      chat:
        options:
          model: gpt-4
    ollama:
      chat:
        options:
          model: mistral:7b
